name: League of Minecraft
version: 0.2.5
description: League of Legends in Minecraft
author: Elicis & Multidude

main: de.elicis.lom.Main

commands:
  lom:
    description: Main Command
    usage: /<command> help
    aliases: